---

# Install tasks for Redhat family
# -----------------------------------------------------------------------------

- name: 'INSTALL | YUM | Install sys FS utils packages'
  become: True
  yum:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  notify: 'HANDLER | Restart sysfsutils service'
  with_items: "{{ sysfs_packages }}"
