---

# Main tasks file for sysfs role

- name: 'INIT | Manage variables to use for our target'
  import_tasks: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::sysfs'
    - 'role::sysfs::config'
    - 'role::sysfs::init'
    - 'role::sysfs::install'


- name: 'INSTALL | Manage sysfs utils installation tasks'
  include_tasks: "{{ role_path }}/tasks/install/{{ ansible_os_family | lower }}_family.yml"
  tags:
    - 'role::sysfs'
    - 'role::sysfs::install'


- name: 'CONFIG | Manage sysfs rules tasks'
  include_tasks: "{{ role_path }}/tasks/manage_config.yml"
  tags:
    - 'role::sysfs'
    - 'role::sysfs::config'


- name: 'CONFIG | Manage sysfs service'
  include_tasks: "{{ role_path }}/tasks/manage_service.yml"
  tags:
    - 'role::sysfs'
    - 'role::sysfs::config'
    - 'role::sysfs::install'
